### ISSUE TITLE
This bundle is invalid - The file extension must be .zip.

### ISSUE THREAD

**Issue by mente** [CocoaPods/swift#21] opened 2015-01-06 11:48 UTC
Hello,

I'm really new to iOS development and especially how iOS builds are made. Working with project locally is just fine (using simulator). But I can't push build to any distribution system (testflight or Beta from Crashlytics). In fact it's pushed in both cases but in case of Crashlytics Beta it fails to install, in case of testflight I receive warning

```
This bundle is invalid - The file extension must be .zip.
```

Problem appeared when I've added swift frameworks to `Podfile`. Here's an example of my `Podfile`:
```ruby
platform :ios, "8.0"

pod "NSLogger" #not used in project itself
pod "HanekeSwift", :git => "https://github.com/Haneke/HanekeSwift", :branch => "podspec"
```

In fact there are more pods but including at least one swift framework gives me such an error.
I can provide you any other information but I don't know which one is valuable. Logs, archives, xcodeproj?

Tried both 0.36.0.beta.1 and HEAD revision of pod

**Comment by ValCapri** [comment] 2015-01-06 15:03
Did you try to remove Pods folder and Podfile and re-do a fresh pod install?
I had this problem some time ago, I don't remember how I solve it.
I have successfully posted an app using CocoaPods 0,36.beta.1 to,Crashlytics and App Store.
The only problem I had was that Apple don't want to validate an iOS 7 compatible app with a dynamic framework (you must use a deployment target >= 8.0 like yours).

**Comment by mente** [comment] 2015-01-06 15:07
It was my original thought but I didn't try. Otherwise it should be noted somewhere in [announcement of swift support](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/). 

Anyway you might be right. Will give it a try.

**Comment by mente** [comment] 2015-01-12 12:12
So I've tried recreating project several times with no luck. I narrowed down problem a bit to `use_frameworks!` without any swift dependencies, so my Podfile looks like this:

```ruby
platform :ios, "8.0"

use_frameworks!
pod "NSLogger" #Not used in real project
```

And with this I still experience problem publishing build. Any clues?

**Comment by ValCapri** [comment] 2015-01-12 20:33
No, maybe creating a repository with some example code that doesn't work for you can help.

**Comment by mente** [comment] 2015-01-12 23:09
I've created a [repo](https://github.com/mente/cocoapods-swift-issue) with an example project. Have a look

**Comment by Pasta** [comment] 2015-01-23 05:26
Did you solved this @mente ?

**Comment by mente** [comment] 2015-01-23 07:36
Nope

**Comment by Pasta** [comment] 2015-01-23 16:14
I guess the solution is to not use cocoapods until 0.36 is released.

**Comment by mente** [comment] 2015-01-24 22:33
It's one way of the fix. But I couldn't find a similar issue in the internet so thought it could be just me. So just wanted to ensure that I'm doing everything correct

**Comment by albertbori** [comment] 2015-01-26 22:25
Having the same issue, but only when deploying with a custom Scheme and Build Configuration. I'm guessing I don't have it set up correctly. If I use the standard Scheme and Build Configuration (Debug/Release), then I am able to deploy to iTunes Connect just fine.

**Comment by segiddins** [comment] 2015-01-26 22:29
@neonichu this seems to be another custom config issue?

**Comment by Aahung** [comment] 2015-01-27 09:44
I also have this issue.

**Comment by neonichu** [comment] 2015-01-27 09:47
Could anyone of you put an example project up that causes this? Currently unsure how to reproduce.

**Comment by Aahung** [comment] 2015-01-27 09:49
My Podfile is
```
platform :ios, '8.0'

target '***' do

pod 'JLToast'
pod 'Alamofire', '~> 1.1'

end
```
and I am trying to add `use_frameworks!`

**Comment by Aahung** [comment] 2015-01-27 10:50
Guys, I think I found something, I unzip the .ipa files
![ipa can pass iTunesConnect](https://cloud.githubusercontent.com/assets/3804518/5917180/098a57ec-a655-11e4-9d30-db9ebe610de0.png)
![ipa saids "invalid binary"](https://cloud.githubusercontent.com/assets/3804518/5917204/32acd938-a655-11e4-83e1-e61e9c1d0ce1.png)
It seems Cocoapods forget to copy the frameworks instead it just create a link: (`ls -l` in terminal)
`lrwxr-xr-x  1 Hung  staff      235 Jan 27 18:44 JLToast.framework -> /Users/Hung/Library/Developer/Xcode/DerivedData/CityU_Sport_Facility-bmxqvxilvqqmqldcflwwgzqhebbs/Build/Intermediates/ArchiveIntermediates/CityU Sport Facility Looking Up/IntermediateBuildFilesPath/UninstalledProducts/JLToast.framework`

**Comment by neonichu** [comment] 2015-01-27 10:58
That should have been fixed by #2871 - what's the difference between those two results, first one doing manual integration of Alamofire?

**Comment by Aahung** [comment] 2015-01-27 11:07
This is the only visible difference between the two archive. I think maybe it causes failure.

**Comment by albertbori** [comment] 2015-01-27 17:12
@neonichu, this only happens to me when using a custom build configuration. See if the following causes it for you:

1. `Project` -> `Info` -> `Configurations` -> `+` -> `Duplicate "Release" Configuration`. 
1. Name it `QA`. 
1. Reference a swift framework
1. Run `pod install`, and you'll get a warning about pods not setting the base configuration for `MyProject.qa.xcconfig`.
1. Find `Pods/Target Support Files/Pods/Pods.qa.xcconfig` and drag it into your main project
1. Change your `QA` Base Configuration File to `Pods.qa`.
1. Change your schema to build the project using the `QA` build configuration
1. Archive your main project
1. Export it
1. Examine the contents against a build using `Release` build configuration

**Comment by albertbori** [comment] 2015-02-06 00:50
I also extracted the two .ipa files to compare, and found this difference:
![screen shot 2015-02-05 at 5 46 15 pm](https://cloud.githubusercontent.com/assets/1742709/6072477/69291754-ad5f-11e4-881e-e72d144e1dc0.png)

`QA` build config on the left, `Release` build config on the right

**Comment by albertbori** [comment] 2015-02-06 04:41
After implementing `use_frameworks!`, not even my `Release` build config is working now. I can confirm what @Aahung was saying, after examining the .app package contents. It's very clear that the **alias** to the framework is being copied into the .app package, instead of the actual framework files:

![screen shot 2015-02-05 at 9 33 57 pm](https://cloud.githubusercontent.com/assets/1742709/6074615/8d60138c-ad7f-11e4-9bce-b45b554df9a7.png)

**Comment by danilotorrisi** [comment] 2015-02-08 11:30
I have the exact same issue here, as you've already said the problem is related to the **aliases**. Have you find any kind of workaround?

**Comment by Aahung** [comment] 2015-02-08 11:42
I plan to wait for the stable version of cocoapods. Right now I use objective c.

**Comment by danilotorrisi** [comment] 2015-02-08 12:08
I'll also wait for the stable version, but I was trying to deploy just the beta version for now. 

I've tried to manually copy the frameworks from the intermediate folder path ( where the aliases point to ) to the app framework folder. I'm trying to upload the binary to iTunes Connect, I'll let you know if that worked.

**Comment by albertbori** [comment] 2015-02-09 18:31
Just found an interesting warning in the build log (report navigator) in Xcode:

> /Users/me/dev/myproject/MyProject/../Pods/Target Support Files/Pods/Pods-frameworks.sh: line 14: [: /Users/me/Library/Developer/Xcode/DerivedData/MyProject-ecinfzhnelbxxegrpzcpwnezmvot/Build/Intermediates/ArchiveIntermediates/MyProject: binary operator expected

**Comment by albertbori** [comment] 2015-02-09 19:06
Symlink copy was failing because of spaces in the `source` path. I have a pull-request in to fix this, and have verified that the fix allows the build through the app-store screening.

**Closed** 2015-02-09 19:30 UTC
